new Word("filler", { "stinky":"filler", "shiny":"filler", "orange":"filler", "moody":"filler", "clean":"filler", "dirty":"filler", "aromatic":"filler", "dull":"filler", "calm":"filler", "serene":"filler", "blue":"filler", "metallic":"filler", "clear":"filler", "narrow":"filler", "broad":"filler", "huge":"filler", "tiny":"filler", "cocky":"filler", "thick":"filler", "thin":"filler", "smooth":"filler", "rough":"filler", "awkward":"filler", "clumsy":"filler", "sophisticated":"filler", "expensive":"filler", "cheap":"filler", "distressed":"filler", "flustered":"filler", "vast":"filler", "sexy":"filler", "nerdy":"filler", "geeky":"filler", "charming":"filler", "cute":"filler", "blonde":"filler", "ugly":"filler", "plain":"filler", "complex":"filler", "simple":"filler", "bald":"filler", "hairy":"filler", "decorated":"filler", "embellished":"filler", "energetic":"filler", "wooden":"filler", "graceful":"filler", "gawky":"filler", "marble":"filler", "muddy":"filler", "grungy":"filler", "crystal":"filler", "glass":"filler"}, false)

new Word("cold", {"algid": "synonym", "arctic": "synonym", "bitter": "synonym", "bone-chilling": "synonym", "chill": "synonym", "cool": "synonym", "freezing": "synonym", "frigid": "synonym", "frosty": "synonym", "gelid": "synonym", "glacial": "synonym", "icy": "synonym", "nippy": "synonym", "numbing": "synonym", "polar": "synonym", "shivery": "synonym", "snappy": "synonym", "wintry": "synonym", "antiseptic": "synonym", "brittle": "synonym", "clammy": "synonym", "frozen": "synonym", "hard-eyed": "synonym", "unfriendly": "synonym", "unsympathetic": "synonym", "aloof": "synonym", "antisocial": "synonym", "buttoned-up": "synonym", "detached": "synonym", "distant": "synonym", "dry": "synonym", "offish": "synonym", "remote": "synonym", "standoffish": "synonym", "unbending": "synonym", "ardent": "antonym", "blazing": "antonym", "boiling": "antonym", "broiling": "antonym", "burning": "antonym", "fervent": "antonym", "fervid": "antonym", "fiery": "antonym", "glowing": "antonym", "hot": "antonym", "igneous": "antonym", "molten": "antonym", "roasting": "antonym", "scalding": "antonym", "scorching": "antonym", "searing": "antonym", "seething": "antonym", "sizzling": "antonym", "sultry": "antonym", "sweltering": "antonym", "torrid": "antonym", "warming": "antonym", "cordial": "antonym", "friendly": "antonym", "genial": "antonym", "happy": "antonym", "hearty": "antonym", "sympathetic": "antonym", "warm": "antonym", "sociable": "antonym"})

new Word("elastic", {"bouncy": "synonym", "flexible": "synonym",  "resilient": "synonym",  "rubbery": "synonym",  "springy": "synonym",  "stretch": "synonym",  "supple": "synonym",  "whippy": "synonym",  "adaptable": "synonym",  "adjustable": "synonym", "alterable": "synonym",  "changeable": "synonym",  "fluid": "synonym",  "malleable": "synonym",  "modifiable": "synonym",  "pliable": "synonym",  "variable": "synonym", "inelastic": "antonym", "inflexible": "antonym",  "non-elastic": "antonym", "rigid": "antonym", "stiff": "antonym",  "established": "antonym",  "fixed": "antonym", "immutable": "antonym", "ramrod": "antonym",  "set": "antonym", "invariable": "antonym", "unbudgeable": "antonym", "unchangeable": "antonym", "non-malleable": "antonym", "unadaptable": "antonym", "unalterable": "antonym" })

new Word("serious", {"earnest": "synonym", "grave": "synonym",  "humorless": "synonym",  "no-nonsense": "synonym",  "po-faced": "synonym",  "sedate": "synonym",  "severe": "synonym",  "sober": "synonym",  "solemn": "synonym",  "staid": "synonym",  "weighty": "synonym",  "heavy": "synonym", "facetious": "antonym", "flippant": "antonym",  "humorous": "antonym",  "jesting": "antonym",  "jocular": "antonym", "joking": "antonym",  "ludic": "antonym",  "playful": "antonym",  "light": "antonym"})

new Word("delicate", {"airy": "synonym", "dainty": "synonym", "exquisite": "synonym",  "nuanced": "synonym", "refined": "synonym", "subtle": "synonym", "acute": "synonym", "fine": "synonym", "keen": "synonym", "perceptive": "synonym", "quick": "synonym", "sensitive": "synonym", "sharp": "synonym", "breakable": "synonym", "fragile": "synonym", "frail": "synonym", "frangible": "synonym", "robust": "antonym", "strong": "antonym", "sturdy": "antonym", "infrangible": "antonym", "non-breakable": "antonym", "durable": "antonym",  "resistant": "antonym", "tough": "antonym", "rugged": "antonym", "solid": "antonym", "sound": "antonym"})

new Word("determined", {"bound": "synonym", "decisive": "synonym",  "do-or-die": "synonym",  "firm": "synonym",  "hell-bent": "synonym",  "intent": "synonym",  "purposeful": "synonym",  "resolute": "synonym", "resolved": "synonym", "single-minded": "synonym", "unyielding": "synonym", "dogged": "synonym", "grim": "synonym", "implacable": "synonym", "relentless": "synonym", "unappeasable": "synonym", "unflinching": "synonym", "unrelenting": "synonym", "faltering": "antonym", "hesitant": "antonym", "indecisive": "antonym", "irresolute": "antonym", "unresolved": "antonym", "vacillating": "antonym", "wavering": "antonym",  "weak-kneed": "antonym", "slackening": "antonym", "yielding": "antonym"})

new Word("delicious", { "appetizing":"synonym", "delectable":"synonym", "delish":"synonym", "mouthwatering":"synonym", "scrumptious":"synonym", "tasty":"synonym", "yummy":"synonym", "palatable":"synonym", "luscious":"synonym", "succulent":"synonym", "savory":"synonym", "flavorsome":"synonym","luscious":"synonym", "distasteful":"antonym", "flavorless":"antonym", "flat":"antonym", "unappetizing":"antonym", "stale":"antonym", "unpalatable":"antonym", "tasteless":"antonym", "yucky":"antonym", "insipid":"antonym", "unsavory":"antonym", "unpleasant":"antonym"})

new Word("loud", { "blaring":"synonym", "blasting":"synonym", "earsplitting":"synonym", "roaring":"synonym", "thundering":"synonym", "extravagant":"synonym", "over-the-top":"synonym", "gaudy":"synonym", "thunderous":"synonym", "piercing":"synonym", "noisy":"synonym", "gentle":"antonym", "soft":"antonym", "low":"antonym", "conservative":"antonym", "quiet":"antonym", "understated":"antonym", "unflamboyant":"antonym", "unflashy":"antonym"})

new Word("brave", { "bold":"synonym", "courageous":"synonym", "fearless":"synonym", "gutsy":"synonym", "heroic":"synonym", "stalwart":"synonym", "valiant":"synonym", "audacious":"synonym", "unafraid":"synonym", "lionhearted":"synonym", "dauntless":"synonym", "undeterred":"synonym", "chicken":"antonym", "cowardly":"antonym", "craven":"antonym", "dastardly":"antonym", "fainthearted":"antonym", "fearful":"antonym", "gutless":"antonym", "yellow":"antonym", "lily-livered":"antonym", "spineless":"antonym", "weakhearted":"antonym", "uncourageous":"antonym", "unheroic":"antonym"})

new Word("slow", { "sluggish":"synonym", "snail-paced":"synonym", "tardy":"synonym", "unhurried":"synonym", "leisurely":"synonym", "crawling":"synonym", "dragging":"synonym", "languid":"synonym", "dawdling":"synonym", "dillydallying":"synonym", "brisk":"antonym", "rapid":"antonym", "warp-speed":"antonym", "hurrying":"antonym", "quick":"antonym", "speedy":"antonym", "swift":"antonym", "rushing":"antonym", "flying":"antonym", "bolting":"antonym", "fast":"antonym"})

new Word("good", { "alright":"synonym", "acceptable":"synonym", "decent":"synonym", "just":"synonym", "moral":"synonym", "true":"synonym", "well":"synonym", "virtuous":"synonym", "nice":"synonym", "right":"synonym", "ethical":"synonym", "satisfactorily":"synonym", "fine":"synonym", "bad":"antonym", "dishonest":"antonym", "evil":"antonym", "immoral":"antonym", "indecent":"antonym", "unethical":"antonym", "unrighteous":"antonym", "unsatisfactory":"antonym", "wrong":"antonym", "deficient":"antonym", "lousy":"antonym"})

new Word("maneuver", { "address":"synonym", "field":"synonym", "manage":"synonym", "handle":"synonym", "manipulate":"synonym", "negotiate":"synonym", "contrive":"synonym", "finagle":"synonym", "finesse":"synonym", "engineer":"synonym", "mastermind":"synonym", "wangle":"synonym", "frame":"synonym", "botch":"antonym", "bungle":"antonym", "fumble":"antonym", "mishandle":"antonym", "booble":"antonym", "butcher":"antonym", "louse-up":"antonym", "muff":"antonym", "mess":"antonym", "mangle":"antonym", "goof":"antonym"})

new Word("manifest", { "apparent":"synonym", "barefaced":"synonym", "clear-cut":"synonym", "decided":"synonym", "distinct":"synonym", "evident":"synonym", "lucid":"synonym", "obvious":"synonym", "patent":"synonym", "straightforward":"synonym", "transparent":"synonym", "unmistakable":"synonym", "ringing":"synonym", "ambiguous":"antonym", "clouded":"antonym", "cryptic":"antonym", "dark":"antonym", "enigmatic":"antonym", "equivocal":"antonym", "indistinct":"antonym", "mysterious":"antonym", "obscure":"antonym", "unclear":"antonym", "obfuscated":"antonym", "unclarified":"antonym"})

new Word("rambling", { "desultory":"synonym", "digressional":"synonym", "excursive":"synonym", "leaping":"synonym", "maundering":"synonym", "meandering":"synonym", "discursive":"synonym", "wandering":"synonym", "circuitous":"synonym", "straightforward":"synonym", "transparent":"synonym", "diffuse":"synonym", "garrulous":"synonym", "verbose":"synonym", "wordy":"synonym", "windy":"synonym", "long-winded":"synonym", "coherent":"antonym", "consistent":"antonym", "logical":"antonym", "direct":"antonym", "focused":"antonym", "straightforward":"antonym", "undeviating":"antonym", "compact":"antonym", "concise":"antonym", "crisp":"antonym", "terse":"antonym", "pithy":"antonym", "succinct":"antonym"})

new Word("rapture", { "cloud-nine":"synonym", "elatedness":"synonym", "elation":"synonym", "euphoria":"synonym", "exhilaration":"synonym", "heaven":"synonym", "high":"synonym", "intoxication":"synonym", "paradise":"synonym", "ecstasy":"synonym", "rhapsody":"synonym", "seventh-heaven":"synonym", "swoon":"synonym", "transport":"synonym", "misery":"antonym", "sadness":"antonym", "woe":"antonym", "wretchedness":"antonym", "dejection":"antonym", "desolation":"antonym", "despair":"antonym", "despondency":"antonym", "doldrums":"antonym", "dumps":"antonym", "forlornness":"antonym", "mopes":"antonym", "melancholy":"antonym", "gloom":"antonym", "heartsickness":"antonym"})

new Word("piety", { "devotion":"synonym", "faith":"synonym", "steadfastness":"synonym", "blessedness":"synonym", "devoutness":"synonym", "godliness":"synonym", "allegiance":"synonym", "piousness":"synonym", "commitment":"synonym", "loyalty":"synonym", "sanctity":"synonym", "atheism":"antonym", "godlessness":"antonym", "unholiness":"antonym", "disloyalty":"antonym", "faithlessness":"antonym", "falseness":"antonym", "inconstancy":"antonym", "infidelity":"antonym", "perfidiousness":"antonym", "treachery":"antonym", "unfaithfulness":"antonym"})

new Word("hurdle", { "balk":"synonym", "bar":"synonym", "block":"synonym", "deterrent":"synonym", "crimp":"synonym", "hindrance":"synonym", "holdback":"synonym", "encumbrance":"synonym", "impediment":"synonym", "inhibition":"synonym", "interference":"synonym", "obstacle":"synonym", "obstruction":"synonym", "shackles":"synonym", "trammel":"synonym", "catalyst":"antonym", "goad":"antonym", "impetus":"antonym", "incentive":"antonym", "spur":"antonym", "stimulant":"antonym", "advantage":"antonym", "break":"antonym", "edge":"antonym", "benefit":"antonym", "boost":"antonym", "help":"antonym", "handmaiden":"antonym", "assistance":"antonym"})







// new Word("filler", {})
